services:
  - type: web
    name: npc-engine
    env: python
    region: oregon
    plan: starter
    buildCommand: ./build.sh
    startCommand: python3 render_start.py
    envVars:
            - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health 